services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scorecard
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/scorecard
    ports: ["8000:8000"]
    depends_on: ["db"]
volumes:
  pgdata:
